rbac/urls.py
from django.urls import path,include,re_path
from django.views.decorators.csrf import csrf_exempt

from rbac import views
app_name = 'rbac'
urlpatterns = [
    re_path(r'^user/list/$',views.UserInfo.as_view(),name='user_list'),
    # re_path(r'^user/del/(?P<uid>\d+)/$', views.user_del, name='user_del'),
    re_path(r'^user/del/$', views.user_del, name='user_del'),
    re_path(r'^user/edit/(?P<uid>\d+)/$', views.user_edit, name='user_edit'),
    re_path(r'^user/add/$', views.user_add, name='user_add'),
    re_path(r'^chat/$',csrf_exempt(views.Chat.as_view()),name='chat'),
    re_path(r'^user/batch_del/$',views.user_batch_del,name='user_batch_del'),
    re_path(r'^url/(?P<proj>(g|r|l))/index/$',views.proj_index,name='proj_index'),

]

rbac/models.py
from django.db import models

class User(models.Model):

    gender_choice=(
        (0,'男'),
        (1,'女')
    )
    project_choice=(
        ('g','G项目'),
        ('l','L项目'),
        ('r','R项目')
    )

    name = models.CharField(max_length=30,unique=True,verbose_name='姓名')

    age = models.IntegerField(verbose_name='年龄')

    gender = models.IntegerField(choices=gender_choice,verbose_name='性别')

    telephone = models.IntegerField(verbose_name='电话')

    role=models.ForeignKey(to='Role',on_delete=models.CASCADE)

    project = models.CharField(choices=project_choice,max_length=20,verbose_name='项目')

    def __str__(self):
        return self.name

class Role(models.Model):

    title = models.CharField(max_length=30,verbose_name='角色')

    def __str__(self):
        return self.title


class CR(models.Model):

    user = models.CharField(max_length=20)
    channel = models.CharField(max_length=30)

rbac/forms.py
from django import forms
from rbac import models

class UserForm(forms.ModelForm):

    class Meta:

        model = models.User
        fields = '__all__'

        widgets={
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'age': forms.TextInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'telephone': forms.TextInput(attrs={'class': 'form-control'}),
            'role':forms.Select(attrs={'class': 'form-control'}),

        }

rbac/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse,HttpResponse
from django.views import View
from rbac.models import User,Role
from rbac.forms import UserForm
from django.views.decorators.csrf import csrf_exempt
from . import consumers
from django.utils.safestring import mark_safe
import json

# Create your views here.

class UserInfo(View):

    def get(self,request):

        users = User.objects.all()

        return render(request, 'user.html', {'users':users})

    def post(self,request):

        data= request.POST['case']
        print(data)

class Chat(View):

    def get(self,request):
        return render(request, 'chat.html')


    def post(self,request):
        print('@@@@@@@@@@@@@@@@@@')
        user_group = str(request.user) + '_ws_rbac_chat_'
        print(user_group)
        content = request.POST.get('content')
        print(content)
        # print(request.POST['content'])

        # user_group = '{user}_{path}'.format(user=user,path=path)
        for x in range(int(content)):
            out = "正在打印第{num}个数字".format(num=x)
            consumers.SendMsg(user_group,message=out)

        data = {
            'received': True
        }
        # print(request.POST)
        return JsonResponse(data)




def user_del(request):

    if request.method == 'GET':
        uid = request.GET.get('uid')

        User.objects.filter(id=uid).first().delete()
        # # print(request)
        # return redirect('rbac:user_list')
        data = {
            'deleted': True
        }
        return JsonResponse(data)

def proj_index(request,proj):
    users = User.objects.filter(project=proj).all()
    proj_url = proj

    return  render(request,'user.html',locals())



def user_edit(request,uid):
    obj = User.objects.filter(id=uid).first()
    if request.method == 'GET':
        form = UserForm(instance=obj)
        return render(request, 'user_edit.html', {'form':form})
    else:
        form = UserForm(data=request.POST,instance=obj)
        if form.is_valid():
            form.save()
            return redirect('rbac:user_list')
        else:
            return render(request, 'user_edit.html', {'form':form})

def user_add(request):
    if request.method == 'GET':
        form = UserForm()
    else:
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('rbac:user_list')
        else:
            return redirect('rbac:user_list',{'form':form})

    return render(request, 'user_add.html', {'form':form})

@csrf_exempt
def user_batch_del(request):


    checkval =  (request.POST.getlist('checkval'))

    for uid in checkval:
        User.objects.filter(id=uid).first().delete()
    data = {
        'deleted': True
    }
    return JsonResponse(data)

rbac/templates/base.html
{% load static %}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}base{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlet-2.4.10/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
  <link rel="stylesheet" href="{% static 'adminlet-2.4.10/dist/css/skins/skin-blue.min.css' %}">

    {% block css %}{% endblock %}

</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>x-project {{ proj|upper }}项目</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>x-project {{ proj|upper }}项目</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the messages -->
                <ul class="menu">
                  <li><!-- start message -->
                    <a href="#">
                      <div class="pull-left">
                        <!-- User Image -->
                        <img src="{% static 'adminlet-2.4.10/dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
                      </div>
                      <!-- Message title and timestamp -->
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <!-- The message -->
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <!-- end message -->
                </ul>
                <!-- /.menu -->
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>
          <!-- /.messages-menu -->

          <!-- Notifications Menu -->
          <li class="dropdown notifications-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">10</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>
                <!-- Inner Menu: contains the notifications -->
                <ul class="menu">
                  <li><!-- start notification -->
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                  </li>
                  <!-- end notification -->
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>
          <!-- Tasks Menu -->
          <li class="dropdown tasks-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-flag-o"></i>
              <span class="label label-danger">9</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- Inner menu: contains the tasks -->
                <ul class="menu">
                  <li><!-- Task item -->
                    <a href="#">
                      <!-- Task title and progress text -->
                      <h3>
                        Design some buttons
                        <small class="pull-right">20%</small>
                      </h3>
                      <!-- The progress bar -->
                      <div class="progress xs">
                        <!-- Change the css width attribute to simulate progress -->
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                </ul>
              </li>
              <li class="footer">
                <a href="#">View all tasks</a>
              </li>
            </ul>
          </li>
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="{% static 'adminlet-2.4.10/dist/img/user2-160x160.jpg' %}" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">系统管理员</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="{% static 'adminlet-2.4.10/dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">

                <p>
                  系统管理员
                  <small>2019-4-12</small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{% static 'adminlet-2.4.10/dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Admin</p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i>在线</a>
        </div>
      </div>

      <!-- search form (Optional) -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
        </div>
      </form>
      <!-- /.search form -->

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">导航栏{{ proj }}</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="/rbac/url/{{ proj }}/index/"><i class="fa fa-dashboard"></i> <span>用户管理</span></a></li>
        <li><a href="/chat/url/{{ proj }}/index/"><i class="fa fa-table"></i> <span>Channel</span></a></li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">

    {% block breadcrumb %}{% endblock %}

    <!-- Main content -->
    <section class="content container-fluid">
        {#        主体内容全放到这里！#}
        {% block content %}{% endblock %}
    </section>
    <!-- /.content -->

  </div>
  <!-- /.content-wrapper -->


  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">

    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2019 <a href="" target="_blank"></a>.</strong> All rights reserved.
  </footer>


</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script src="{% static 'adminlet-2.4.10/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'adminlet-2.4.10/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlet-2.4.10/dist/js/adminlte.min.js' %}"></script>

{% block script %}{% endblock %}

<script>
    $('ul.sidebar-menu li').each(function(i){
        if($(this).children().first().attr('href')==='{{ request.path }}'){
            $(this).addClass('active');
        }else{
        }
    });
</script>
</body>
</html>

rbac/templates/chat.html
{% extends 'base.html' %}
{% load static %}
{% block title %}聊天室{% endblock %}
{% block css %}{% endblock %}

{% block breadcrumb %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        聊天室
      </h1>

    </section>
{% endblock %}

{% block content %}

    <div class="col-md-6" id="tab_2">

      <div class="box-body">

           <input type="text" class="form-control" id="content" placeholder="请输入一个整数">
          <button type="submit" class="btn btn-primary" onclick="send_chat()" >发送</button>

      </div>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            <label>日志</label>
            <textarea  id="chat-log" class="form-control" cols="100" rows="20" placeholder="操作日志.." disabled=""></textarea>
        </div>
</div>

{% endblock %}

{% block script %}
    <script>


    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/rbac/chat/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];

        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };


</script>



<script>

function send_chat() {
    var content  = $("#content").val()
    document.querySelector('#chat-log').value = "";
    $.ajax({
        url: '{% url 'rbac:chat' %}',
        type: 'POST',
        data: {
            'content': content,
        },
        dataType: 'json',
        success: function (data) {
            if (data.received) {
              confirm("数据已经处理完")
            }
        }
    });

}

</script>


{% endblock %}

rbac/templates/proj.html
{% load static %}
你访问的{{ pj|upper }}项目

rbac/templates/user.html
{% extends 'base.html' %}
{% load static %}
{% block title %}用户管理{% endblock %}
{% block css %}{% endblock %}

{% block breadcrumb %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        用户管理
      </h1>

    </section>
{% endblock %}

{% block content %}

        <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

        <div class="box">

        <!-- /.box-header -->
        <div class="box-body">
            <a href="{% url 'rbac:user_add' %}" class="btn btn-primary">添加</a>
            <button id="batch-del" type="submit" class="btn btn-danger" onclick="BatchUserDelete()" >批量删除</button>
          <table id="userTable" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th><input type="checkbox" id="selectall"/></th>
              <th>id</th>
              <th>姓名</th>
              <th>年龄</th>
              <th>性别</th>
              <th>电话</th>
              <th>角色</th>
              <th>所属项目</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
             {% for user in users %}
                <tr id="user-{{ user.id }}">
                  <td align="center"><input type="checkbox" class="case" name="case" value="{{ user.id }}" /></td>
                  <td>{{ user.id }}</td>
                  <td>{{ user.name }}</td>
                  <td>{{ user.age }}</td>
                  <td>{{ user.get_gender_display }}</td>
                  <td>{{ user.telephone }}</td>
                  <td>{{ user.role }}</td>
                  <td>{{ user.get_project_display }}</td>
                  <td><a href="{% url 'rbac:user_edit' user.id %}" class="btn btn-primary">编辑</a>
                      <a href="javascript:void(0)"  onclick="deleteUser({{ user.id }})" class="btn btn-primary" role="button">删除</a></td>
                  </td>
                </tr>
            {% endfor %}

            </tbody>

          </table>

        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
        </div>
    <!-- /.col -->
      </div>
    <!-- /.row -->
    </section>



{% endblock %}

{% block script %}

<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>

<script>
$(function () {
        $('#userTable').DataTable({
          "paging": true,       <!-- 允许分页 -->
          "lengthChange": true, <!-- 允许改变每页显示的行数 -->
          "searching": true,    <!-- 允许内容搜索 -->
          "ordering": true,     <!-- 允许排序 -->
          "info": true,         <!-- 显示信息 -->
          "autoWidth": false    <!-- 固定宽度 -->
        });
      });
</script>

<script>

function deleteUser(uid) {
  var action = confirm("确定要删除这个用户吗?");
  if (action != false) {
    $.ajax({
        url: '{% url 'rbac:user_del' %}',
        data: {
            'uid': uid,
        },
        dataType: 'json',
        success: function (data) {
            if (data.deleted) {
              $("#userTable #user-" + uid).remove();
            }
        }
    });
  }
}
</script>

<script>
function BatchUserDelete() {
  var checkval = new  Array()
  var checked=$("input[name='case']:checked");
  console.log(checked)
  for(var i=0;i<checked.length;i++)
  {
      {#checked[i].value;#}
      {#checkval += $(checked[i]).val() + ',';#}
      checkval[i] = $(checked[i]).val();
    };
  console.log(checkval)
  if(checked.length == 0){
    alert("至少选中一个用户");
    return false;

  }
  var action = confirm("确定要删除这批用户吗?");
  if (action != false) {
    $.ajax({
        url: '{% url 'rbac:user_batch_del' %}',
        type: 'POST',
        data: {'checkval':checkval},
        dataType: 'json',
        traditional :true,
        success: function (data) {
            if (data.deleted) {
                for (var uid in checkval) {
                    console.log(uid)
                    $("#userTable #user-" + checkval[uid]).remove();
                }
            }
        }
    });
  }
}

</script>

<script>
$(function(){

	// add multiple select / deselect functionality
	$("#selectall").click(function () {
		  $('.case').attr('checked', this.checked);
	});

	// if all checkbox are selected, check the selectall checkbox
	// and viceversa
	$(".case").click(function(){

		if($(".case").length == $(".case:checked").length) {
			$("#selectall").attr("checked", "checked");
		} else {
			$("#selectall").removeAttr("checked");
		}

	});
});



</script>


{% endblock %}

rbac/templates/user_add.html
{% extends 'base.html' %}
{% load static %}
{% block title %}添加用户{% endblock %}
{% block css %}{% endblock %}

{% block breadcrumb %}
    <!-- Content Header (Page header) -->
    <section class="content-header" xmlns="http://www.w3.org/1999/html">
      <h1>
        添加用户
      </h1>

    </section>
{% endblock %}

{% block content %}

        <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

        <div class="box">

        <!-- /.box-header -->
        <div class="box-body" >
        <form method="post" class="">
            {% csrf_token %}
            {% for field in form %}
                <div>{{ field.label }} {{ field }} {{ field.errors.0 }}</div>
            {% endfor %}
            <input type="submit" value="确认" class="btn btn-primary"></input>
            <a href="/rbac/user/list" class="btn btn-primary">取消</a>
        </form>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
        </div>
    <!-- /.col -->
      </div>
    <!-- /.row -->
    </section>



{% endblock %}

{% block script %}

<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>




{% endblock %}

rbac/templates/user_edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}编辑用户{% endblock %}
{% block css %}{% endblock %}

{% block breadcrumb %}
    <!-- Content Header (Page header) -->
    <section class="content-header" xmlns="http://www.w3.org/1999/html">
      <h1>
        编辑用户
      </h1>

    </section>
{% endblock %}

{% block content %}

        <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

        <div class="box">

        <!-- /.box-header -->
        <div class="box-body">
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div>{{ field.label }} {{ field }} {{ field.errors.0 }}</div>
            {% endfor %}
            <input type="submit" value="确认" class="btn btn-primary"></input>
            <a href="/rbac/user/list" class="btn btn-primary">取消</a>
        </form>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
        </div>
    <!-- /.col -->
      </div>
    <!-- /.row -->
    </section>



{% endblock %}

{% block script %}

<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>




{% endblock %}